/**
 * Synthetic `ExportDocument` covering every entry kind: prose, a computation
 * with artifacts (one image, one data file, one skipped file), a rejected
 * verification with a counter-example, a superseded derivation and a final
 * answer. Shared by the renderer tests and the LaTeX compile check.
 */
import { collectSystemPrompts, combinedPromptHash } from "../systemPromptCatalog";
import type { ExportDocument } from "../types";

export const PROMPTS = collectSystemPrompts({ cyAnalyst: false, referenceSeeker: true });

export const DOC: ExportDocument = {
  header: {
    title: "Sum of the first n odd numbers & a test_title",
    conversationId: "conv_123",
    ledgerId: "ledg_root",
    exportedAt: "2026-09-11T12:00:00.000Z",
    createdAt: "2026-09-11T10:00:00.000Z",
    ledgerStatus: "verified",
    reasoningSpeed: "high",
    enabledTools: ["Reference Seeker"],
    models: [
      { role: "main_solver", model: "gpt-5.6-sol", calls: 7 },
      { role: "computation", model: "gpt-5.6-sol", calls: 2 },
      { role: "step_verification", model: "gpt-5.6-sol", calls: 1 },
    ],
    promptsSha256: combinedPromptHash(PROMPTS),
    solverAgentVersion: "1.0.0",
  },
  prompts: [
    {
      index: 0,
      createdAt: "2026-09-11T10:00:00.000Z",
      content: "Show that $\\sum_{k=1}^{n} (2k-1) = n^2$ for all $n \\ge 1$.",
    },
    {
      index: 1,
      createdAt: "2026-09-11T10:30:00.000Z",
      content: "Also check the case n = 100% of 10, i.e. n = 10.",
    },
  ],
  entries: [
    {
      id: "ledg_a1",
      type: "assumption",
      tool: "main_solver",
      status: "accepted",
      reasoningSpeed: "high",
      createdAt: "2026-09-11T10:01:00.000Z",
      dependsOn: [],
      summary: "Let n be a positive integer.",
      body: [
        "We take $n \\in \\mathbb{N}_{\\ge 1}$ and write $S_n = \\sum_{k=1}^{n}(2k-1)$.",
        "",
        "$$\\begin{aligned} S_1 &= 1 \\\\ S_2 &= 4 \\end{aligned}$$",
        "",
        "Costs: $5 and $10 are not math; `$HOME` and `\\[x\\]` in code are not either.",
        "",
        "\\begin{cases} a & b \\\\ c & d \\end{cases}",
        "",
        "The lattice $\\mathbb{Z}^5$ has rank 5.",
      ].join("\n"),
      models: ["gpt-5.6-sol"],
    },
    {
      id: "ledg_d1",
      type: "derivation",
      tool: "main_solver",
      status: "superseded",
      reasoningSpeed: "high",
      createdAt: "2026-09-11T10:02:00.000Z",
      dependsOn: ["ledg_a1"],
      summary: "Wrong closed form.",
      body: "Claim: $S_n = n^2 + 1$. **This is wrong** (see correction).\n\n$$S_{n+1} - S_n = 2n + 1$$",
      models: ["gpt-5.6-sol"],
    },
    {
      id: "ledg_c1",
      type: "symbolic_computation",
      tool: "symbolic",
      status: "accepted",
      reasoningSpeed: "high",
      createdAt: "2026-09-11T10:03:00.000Z",
      dependsOn: ["ledg_a1"],
      summary: "sympy confirms $S_n = n^2$ for symbolic $n$.",
      models: ["gpt-5.6-sol"],
      computation: {
        task: "Compute sum_{k=1}^{n} (2k-1) in closed form with sympy; print the simplified result on the last line.",
        status: "success",
        result: "n**2",
        code: [
          "import sympy as sp  # closed form of the sum, checked for n ≤ 10",
          "",
          "",
          "@functools.lru_cache(maxsize=None)",
          "def partial_sum(n: int) -> int:",
          '    """Return S_n = 1 + 3 + ... + (2n-1) by brute force."""',
          "    return sum(2 * k - 1 for k in range(1, n + 1))",
          "",
          "",
          'n, k = sp.symbols("n k", positive=True, integer=True)',
          "closed = sp.simplify(sp.summation(2*k - 1, (k, 1, n)))",
          "print(closed)",
          "for i in range(1, 11):",
          "    assert partial_sum(i) == i**2, f'mismatch at {i}: {partial_sum(i)} != {i**2}'",
          'print("√ all checks passed → S_n = n²", 0x1F, 1.5e-3)',
          "",
        ].join("\n"),
        codePath: "code/ledg_c1.py",
        stdout: "n**2\n√ all checks passed → S_n = n² 31 0.0015\n",
        durationMs: 1234,
        files: [
          {
            fileId: "file_p1",
            name: "plot 1.png",
            path: "artifacts/ledg_c1/plot_1.png",
            mimeType: "image/png",
            size: 2048,
            isImage: true,
            skipped: false,
          },
          {
            name: "table.csv",
            path: "artifacts/ledg_c1/table.csv",
            mimeType: "text/csv",
            size: 99,
            isImage: false,
            skipped: false,
          },
          {
            name: "huge.npy",
            path: "",
            mimeType: "application/octet-stream",
            size: 10_000_000,
            isImage: false,
            skipped: true,
            reason: "exceeds PYTHON_MAX_ARTIFACT_BYTES",
          },
        ],
      },
    },
    {
      id: "ledg_v1",
      type: "verification",
      tool: "step_verification",
      status: "rejected",
      reasoningSpeed: "high",
      createdAt: "2026-09-11T10:04:00.000Z",
      dependsOn: ["ledg_d1", "ledg_a1"],
      summary: "Step verification of ledg_d1: rejected",
      models: ["gpt-5.6-sol"],
      verification: {
        verdict: "rejected",
        method: "counter-example",
        targetEntryId: "ledg_d1",
        justification: "For $n=1$ the claim gives $S_1 = 2$ but $S_1 = 1$.",
        counterExample: "n = 1",
        focus: "Check the closed form against small n.",
      },
    },
    {
      id: "ledg_f1",
      type: "final_answer",
      tool: "main_solver",
      status: "accepted",
      createdAt: "2026-09-11T10:05:00.000Z",
      dependsOn: ["ledg_c1"],
      summary: "S_n = n^2",
      finalAnswer: "$S_n = n^2$ for every $n \\ge 1$.",
      models: ["gpt-5.6-sol"],
      extraDetails: { note: "kept for the record" },
    },
  ],
  systemPrompts: PROMPTS,
  messages: [
    {
      id: "msg_u0",
      role: "user",
      createdAt: "2026-09-11T10:00:00.000Z",
      content: "Show that $\\sum_{k=1}^{n} (2k-1) = n^2$ for all $n \\ge 1$. <tag>literal</tag>",
      relatedEntries: [],
    },
    {
      id: "msg_a0",
      role: "assistant",
      createdAt: "2026-09-11T10:06:00.000Z",
      content: [
        "The sum of the first $n$ odd numbers is $n^2$:",
        "",
        "$$S_n = \\sum_{k=1}^{n} (2k-1) = n^2.$$",
        "",
        '<img src="/api/conversations/conv_1/files/file_p1" alt="S_n against n" />',
        "",
        '<img src="/api/conversations/conv_1/files/file_missing" alt="not exported" />',
        "",
        "<script>alert(1)</script> [docs](javascript:alert(2)) [ok](https://example.org)",
      ].join("\n"),
      relatedEntries: ["ledg_f1"],
    },
    {
      id: "msg_u1",
      role: "user",
      createdAt: "2026-09-11T10:30:00.000Z",
      content: "Also check the case n = 100% of 10, i.e. n = 10.",
      relatedEntries: [],
    },
  ],
};

